// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfCcIc0wdcywC3ewZbXgnITlNAzuvkLn8',
    appId: '1:268597474969:web:287056670386b8ce7aea08',
    messagingSenderId: '268597474969',
    projectId: 'happy-plant-542fd',
    authDomain: 'happy-plant-542fd.firebaseapp.com',
    storageBucket: 'happy-plant-542fd.appspot.com',
    measurementId: 'G-3TP073C9YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyH_lIh1mfxM8JZyOB0GRmCQJ_LeukIII',
    appId: '1:268597474969:android:028b84509bb2509a7aea08',
    messagingSenderId: '268597474969',
    projectId: 'happy-plant-542fd',
    storageBucket: 'happy-plant-542fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiApvqrwkfc6qjI6T3dat-7ATKllNbdCg',
    appId: '1:268597474969:ios:d84da70dc515bf047aea08',
    messagingSenderId: '268597474969',
    projectId: 'happy-plant-542fd',
    storageBucket: 'happy-plant-542fd.appspot.com',
    iosClientId: '268597474969-kifiifbhcu65unrc0r81ssr2stoun4rg.apps.googleusercontent.com',
    iosBundleId: 'com.example.happyPlant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiApvqrwkfc6qjI6T3dat-7ATKllNbdCg',
    appId: '1:268597474969:ios:37876725ee386ad57aea08',
    messagingSenderId: '268597474969',
    projectId: 'happy-plant-542fd',
    storageBucket: 'happy-plant-542fd.appspot.com',
    iosClientId: '268597474969-hl4h154ker20njs8nf6tvbfctn6mncv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.happyPlant.RunnerTests',
  );
}
